#ifndef COVISE_VERSION_AUTOGEN_H 
#define COVISE_VERSION_AUTOGEN_H 

#define COVISE_VERSION_MAJOR 2020 
#define COVISE_VERSION_MINOR 5 
#define COVISE_VERSION_PATCH 10 

#define COVISE_VERSION_DATE "2020-05-10" 

#define COVISE_VERSION_YEAR 2020
#define COVISE_VERSION_MONTH 5
#define COVISE_VERSION_HASH "734b691bd"

/* TODO maybe better BASEARCHSUFFIX but leave it for now */
#define COVISE_VERSION_ARCH "zebu" 

#endif 
